### Site Settings ###
title               : Abir Jameel
description         : >-
                      "I turn coffee :coffee: into code, use tabs over spaces
                      and never broke production."
                      
baseurl             : "abirjameel.github.io"                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : abirjameel/abirjameel.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU@v1.0.0


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Abir Jameel
  image             : https://bit.ly/2KCvgVJ
  behance           : abirjameel
# dribbble          : abirjameel
  email             : abir47@gmail.com
#  facebook          : your_username
  github            : abirjameel
# gitlab            : your_username
# instagram         : your_username
  linkedin          : linkedin.com/in/abirjameel
  medium            : abirj
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : abir.jameel
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name
#   elements:                                             # For Documentation Only
#     output: False                                        # For Documentation Only


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
#   - scope:                                              # For Documentation Only
#       path: ""                                          # For Documentation Only
#       type: "elements"                                  # For Documentation Only
#     values:                                             # For Documentation Only
#       layout: "element"                                 # For Documentation Only


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
