# site settings
title: ABIR JAMEEL
subtitle: 
email: abir47@gmail.com
description: I build Machine Learning, Deep Learning models and algorithms. 
baseurl:  # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Okhla
city: New Delhi
state: Delhi
zip_code: 110025
country: India
phone: +917204601775

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: github.com/abirjameel
# gitlab_url: 
# googleplus_url: 
# instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/abirjameel/
# pinterest_url:
# slack_url:
twitter_url: https://twitter.com/abirjameel

# build settings
markdown: kramdown

sass:
  style: compressed
  
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
